name: Python package

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    
    steps:
      - uses: actions/checkout@v2
      - name: Build demo
        run: |
          python -m pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish wheel artifact to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          python3 -m pip install twine
          python3 -m twine upload --repository testpypi dist/* --verbose
      - name: Release wheel artifact to PyPI
        if: startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python3 -m pip install twine
          python3 -m twine upload dist/* --verbose
